server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/toystore"
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379
    password: ""

outbound:
  identity:
    providers:
      google:
        client-id: "1007079045635-1pt3idi64hnhht2tiai3t6ja9k8lgtba.apps.googleusercontent.com"
        client-secret: "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"
        redirect-uri: "http://localhost:3000/login?provider=google"
      facebook:
        client-id: "1054506113365796"
        client-secret: "9caa8316ecf56eb2f98f9dc30bd707b9"
        redirect-uri: "http://localhost:3000/login?provider=facebook"

vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "${VNPAY_RETURN_URI:http://localhost:8080/payment/payment-callback}"
  tmn-code: "OCP5JSX3"
  secret-key: "VYO09O0AQKQY0XFLKAVTKLDUM7CZ1TB8"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"

jwt:
  signerKey: "KRiDhgD6MkHRLfg/FjjINYgmy3hqFfLgLQ7QXagiF7O0b70BwWFUkv0y4C4oynus"
  valid-duration: 60
  refreshable-duration: 180
